name: Go application
on:
  push:
   branches:
     - master
     - main
  pull_request:
    types:
      - closed      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check if PR is merged into main/master branch
      if: >
          contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE') ||
          github.event_name == 'pull_request' && github.event.pull_request.merged == true
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "${{ secrets.DOCKERUSR }}" --password-stdin
        docker build ./guestbook-go/ --file ./guestbook-go/Dockerfile -t imprithwish619/go_application:latest 
        docker push imprithwish619/go_application:latest
